name: Build Maven Deploy Lambda

on:
  push:
    branches:
    - backend

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Replace credentials
        run: |
          sed -i 's/DYNAMO_DB_SERVICE_ENDPOINT/${{ secrets.DYNAMO_DB_SERVICE_ENDPOINT }}/g' ./src/main/java/com/marn/visitor/backend/repository/PersonRepository.java
          sed -i 's/DYNAMO_DB_ACCESS_KEY/${{ secrets.DYNAMO_DB_ACCESS_KEY }}/g' ./src/main/java/com/marn/visitor/backend/repository/PersonRepository.java
          sed -i 's/DYNAMO_DB_SECRET_KEY/${{ secrets.DYNAMO_DB_SECRET_KEY }}/g' ./src/main/java/com/marn/visitor/backend/repository/PersonRepository.java
          sed -i 's/VISITOR_DOMAIN_URL/${{ secrets.VISITOR_DOMAIN_URL }}/g' ./src/main/java/com/marn/visitor/backend/repository/PersonRepository.java
          sed -i 's/VISITOR_PROTOCOL/${{ secrets.VISITOR_PROTOCOL }}/g' ./src/main/java/com/marn/visitor/backend/repository/PersonRepository.java
          
      - name: Build with Maven
        run: mvn clean package
      - name: zip
        uses: montudor/action-zip@v0.1.0
        with:
          args: zip -qq -r ./java.zip ./target/springboot-aws-lambda-thesis-0-0-9-aws.jar
      - name: default deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_LAMBDA_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_LAMBDA_SECRET_ACCESS_KEY }}
          aws_region: us-east-1
          function_name: ${{ secrets.AWS_FUNCTION }}
          zip_file: ./target/springboot-aws-lambda-thesis-0-0-9-aws.jar