name: Build Maven Deploy Lambda

on:
  push:
    branches:
    - backend

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Replace credentials
        run: |
          sed -i 's/INFORMACAO/${{ secrets.TESTE_CHANGE }}/g' teste.txt
      - name: to see text
        run: cat teste.txt
      - name: Build with Maven
        run: mvn clean package
      - name: zip
        uses: montudor/action-zip@v0.1.0
        with:
          args: zip -qq -r ./java.zip ./target/springboot-aws-lambda-0.0.1-SNAPSHOT-aws.jar
      - name: default deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_LAMBDA_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_LAMBDA_SECRET_ACCESS_KEY }}
          aws_region: us-east-1
          function_name: ${{ secrets.AWS_FUNCTION }}
          zip_file: ./target/springboot-aws-lambda-0.0.1-SNAPSHOT-aws.jar